
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const tabs=['Inici','Temes','Exàmens','Exercicis','Calculadores','Pràctica','Docent','Progrés','Ajuda'];
let state={tab:'Inici',theme:'',exam:'',query:'',selected:null,level:'Tots'};
const app=$('#app');
function init(){ $('#tabs').innerHTML=tabs.map(t=>`<button onclick="go('${t}')" class="${t===state.tab?'active':''}">${t}</button>`).join(''); render(); }
function go(t){state.tab=t;state.selected=null;init();}
function uniq(a){return [...new Set(a.filter(Boolean))].sort();}
function themes(){return uniq(EXERCISES.map(e=>e.theme));}
function exams(){return uniq(EXERCISES.map(e=>e.exam));}
function filtered(){return EXERCISES.filter(e=>(!state.theme||e.theme===state.theme)&&(!state.exam||e.exam===state.exam)&&(!state.query||JSON.stringify(e).toLowerCase().includes(state.query.toLowerCase()))&&(!state.level||state.level==='Tots'||e.level===state.level));}
function render(){ $('#tabs').innerHTML=tabs.map(t=>`<button onclick="go('${t}')" class="${t===state.tab?'active':''}">${t}</button>`).join(''); ({'Inici':renderHome,'Temes':renderThemes,'Exàmens':renderExams,'Exercicis':renderExercises,'Calculadores':renderCalculators,'Pràctica':renderPractice,'Docent':renderTeacher,'Progrés':renderProgress,'Ajuda':renderHelp}[state.tab])(); }
function renderHome(){app.innerHTML=`<section class="hero"><h2>Benvingut/da</h2><p>Aquesta PWA és una primera versió per treballar els exàmens trimestrals de <b>1r de Batxillerat · Tecnologia Industrial</b>. Permet filtrar exercicis per tema, veure resolucions guiades, imprimir fitxes d’alumne o solucionaris docents i usar calculadores bàsiques.</p><div class="actions"><button class="btn primary" onclick="go('Exercicis')">Començar amb exercicis</button><button class="btn" onclick="go('Temes')">Veure temes</button><button class="btn" onclick="go('Docent')">Preparar classe</button></div></section><div class="grid">${statsCard()}<div class="card"><h3>Com s’ha d’usar?</h3><ol><li>Tria un tema o examen.</li><li>Obre una fitxa.</li><li>Treballa per passos: dades, fórmula, càlcul i interpretació.</li><li>Imprimeix fitxa d’alumne o solucionari docent.</li></ol></div><div class="card"><h3>Nivells N1-N4</h3><p><b>N1</b> identificar · <b>N2</b> calcular · <b>N3</b> interpretar · <b>N4</b> justificar o resoldre problemes complexos.</p></div></div>`}
function statsCard(){return `<div class="card"><h3>Resum del banc</h3><p><b>${EXERCISES.length}</b> exercicis inicials</p><p><b>${themes().length}</b> temes</p><p><b>${exams().length}</b> proves o parcials</p><p><span class="tag good">v1 funcional</span><span class="tag warn">sense servidor</span><span class="tag blue">offline</span></p></div>`}
function filters(){return `<div class="card noPrint"><div class="row"><div><label>Tema</label><select onchange="state.theme=this.value;render()"><option value="">Tots</option>${themes().map(t=>`<option ${state.theme===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Examen</label><select onchange="state.exam=this.value;render()"><option value="">Tots</option>${exams().map(t=>`<option ${state.exam===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Nivell</label><select onchange="state.level=this.value;render()">${['Tots','N1','N2','N3','N4'].map(t=>`<option ${state.level===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label>Cerca</label><input value="${state.query||''}" oninput="state.query=this.value;render()" placeholder="Ohm, energia, motor..."></div></div></div>`}
function card(e){return `<div class="card"><h3>${e.statement.slice(0,68)}${e.statement.length>68?'…':''}</h3><p><span class="tag">${e.theme}</span><span class="tag blue">${e.exam}</span><span class="tag warn">${e.level}</span></p><p class="muted small">${e.type} · ${e.points||''}</p><div class="actions"><button class="btn primary" onclick="openExercise('${e.id}',false)">Obrir</button><button class="btn" onclick="openExercise('${e.id}',true)">Solució model</button></div></div>`}
function renderThemes(){app.innerHTML=`<h2>Temes del curs</h2><p class="muted">Els temes surten dels exàmens trimestrals pujats. Pots preparar classe per tema, no només per examen.</p><div class="grid">${themes().map(t=>{let n=EXERCISES.filter(e=>e.theme===t).length;return `<div class="card"><h3>${t}</h3><p>${n} exercicis</p><div>${uniq(EXERCISES.filter(e=>e.theme===t).flatMap(e=>e.subthemes||[])).slice(0,8).map(s=>`<span class="tag">${s}</span>`).join('')}</div><button class="btn primary" onclick="state.theme='${t.replace(/'/g,"\\'")}';go('Exercicis')">Treballar tema</button></div>`}).join('')}</div>`}
function renderExams(){app.innerHTML=`<h2>Exàmens i proves</h2><div class="grid">${exams().map(x=>`<div class="card"><h3>${x}</h3><p>${EXERCISES.filter(e=>e.exam===x).length} exercicis incorporats</p><button class="btn primary" onclick="state.exam='${x.replace(/'/g,"\\'")}';go('Exercicis')">Obrir prova</button></div>`).join('')}</div>`}
function renderExercises(){ if(state.selected){renderExercise(state.selected);return;} app.innerHTML=`<h2>Exercicis</h2>${filters()}<div class="grid">${filtered().map(card).join('')||'<div class="card">No hi ha resultats.</div>'}</div>`}
function openExercise(id,show){state.selected=id;state.showSolution=show;state.tab='Exercicis';render();}
function renderExercise(id){let e=EXERCISES.find(x=>x.id===id); app.innerHTML=`<div class="card"><div class="actions noPrint"><button class="btn" onclick="state.selected=null;render()">← Tornar</button><button class="btn" onclick="printStudent('${id}')">Imprimir fitxa alumne</button><button class="btn" onclick="printTeacher('${id}')">Imprimir solucionari docent</button><button class="btn" onclick="saveDone('${id}')">Marcar com fet</button></div><h2>${e.theme}</h2><p><span class="tag blue">${e.exam}</span><span class="tag">${e.type}</span><span class="tag warn">${e.level}</span></p><h3>Enunciat</h3><p>${e.statement}</p>${section('Dades',e.data)}${section('Fórmules o idees clau',e.formulas,true)}<h3>Resolució per passos</h3>${e.steps.map((s,i)=>`<div class="step"><b>Pas ${i+1}</b><p>${s}</p><textarea id="ans${i}" placeholder="Resposta de l’alumne per a aquest pas..."></textarea><div class="actions noPrint"><button class="btn" onclick="checkStep('${id}',${i})">Comprovar</button><button class="btn" onclick="hint('${id}',${i})">Pista</button><button class="btn" onclick="showStepSolution('${id}',${i})">Mostra solució del pas</button></div><div id="fb${i}" class="small"></div></div>`).join('')}<div id="fullsol" class="${state.showSolution?'':'hidden'}">${solutionBlock(e)}</div><div class="actions noPrint"><button class="btn primary" onclick="$('#fullsol').classList.toggle('hidden')">Mostrar/amagar solució completa</button></div></div>`}
function section(title,items,formula=false){return `<h3>${title}</h3>${(items||[]).map(x=>`<div class="${formula?'formula':'step'}">${x}</div>`).join('')}`}
function solutionBlock(e){return `<div class="solution"><h3>Solució model</h3><p>${e.solution}</p><h4>Errors habituals</h4><ul>${(e.errors||[]).map(x=>`<li>${x}</li>`).join('')}</ul><h4>Criteris de correcció</h4><table class="table"><tr><th>Aspecte</th><th>Què es valora</th></tr><tr><td>Dades</td><td>Identifica magnituds i unitats.</td></tr><tr><td>Fórmula</td><td>Tria el model adequat.</td></tr><tr><td>Càlcul</td><td>Substitueix i opera ordenadament.</td></tr><tr><td>Interpretació</td><td>Dona resultat amb unitat i explicació.</td></tr></table></div>`}
function hint(id,i){let e=EXERCISES.find(x=>x.id===id);$('#fb'+i).innerHTML=`<div class="step"><b>Pista:</b> ${e.steps[i]}</div>`}
function showStepSolution(id,i){let e=EXERCISES.find(x=>x.id===id);$('#fb'+i).innerHTML=`<div class="solution"><b>Solució orientativa del pas:</b> ${e.solution}</div>`}
function checkStep(id,i){let v=$('#ans'+i).value.trim(); let ok=v.length>18; $('#fb'+i).innerHTML=`<div class="${ok?'result':'step bad'}">${ok?'Resposta prou desenvolupada. Compara-la amb la solució model.':'Resposta massa curta. Escriu dades, fórmula o raonament.'}</div>`; addProgress(id, ok?1:0);}
function printStudent(id){let e=EXERCISES.find(x=>x.id===id);let w=window.open('','_blank');w.document.write(printHtml(e,false));w.document.close();w.print();}
function printTeacher(id){let e=EXERCISES.find(x=>x.id===id);let w=window.open('','_blank');w.document.write(printHtml(e,true));w.document.close();w.print();}
function printHtml(e,teacher){return `<!doctype html><html><head><meta charset="utf-8"><title>Fitxa</title><style>body{font-family:"Times New Roman",serif;margin:28px;color:#111}h1{font-size:22px}h2{font-size:17px;border-bottom:1px solid #999}.box{border:1px solid #999;padding:10px;margin:10px 0}.space{height:90px;border:1px solid #bbb;margin:8px 0}.formula{background:#f2f2f2;padding:6px;margin:4px 0}</style></head><body><h1>${teacher?'Solucionari docent':'Fitxa d’alumne'} · ${e.theme}</h1><p>${e.exam} · ${e.type} · ${e.level}</p><h2>Enunciat</h2><p>${e.statement}</p><h2>Dades</h2>${(e.data||[]).map(x=>`<div class="box">${x}</div>`).join('')}<h2>Passos de resolució</h2>${(e.steps||[]).map((s,i)=>`<div class="box"><b>Pas ${i+1}.</b> ${s}${teacher?'':'<div class="space"></div>'}</div>`).join('')}${teacher?`<h2>Solució model</h2><p>${e.solution}</p><h2>Errors habituals</h2><ul>${(e.errors||[]).map(x=>`<li>${x}</li>`).join('')}</ul>`:''}</body></html>`}
function saveDone(id){let p=JSON.parse(localStorage.ti1progress||'[]');p.push({id,at:new Date().toISOString(),score:null});localStorage.ti1progress=JSON.stringify(p);alert('Exercici guardat al progrés.');}
function addProgress(id,score){let p=JSON.parse(localStorage.ti1progress||'[]');p.push({id,at:new Date().toISOString(),score});localStorage.ti1progress=JSON.stringify(p);}
function renderCalculators(){app.innerHTML=`<h2>Calculadores</h2><p class="muted">Eines ràpides per comprovar exercicis de 1r.</p><div class="grid">${calcCard('Ohm','V = I·R','ohmCalc()','R (Ω)<input id="r" type="number" value="1200">I (A)<input id="i" type="number" value="0.4">')}${calcCard('Potència i energia','P = V·I · E = P·t','peCalc()','P (kW)<input id="pk" type="number" value="2.3">Temps (h)<input id="th" type="number" value="150">')}${calcCard('Sèrie','Req = suma','seriesCalc()','Resistències separades per comes<input id="rs" value="20,40,60">V (V)<input id="vs" type="number" value="12">')}${calcCard('Calor aigua','Q = m·ce·ΔT','waterCalc()','Q (J)<input id="qj" type="number" value="3000">m aigua (kg)<input id="mk" type="number" value="0.05">T inicial (°C)<input id="ti" type="number" value="5">')}${calcCard('Solar','E = H·A·η·dies','solarCalc()','H (kWh/m²·dia)<input id="hh" type="number" value="13">Àrea (m²)<input id="aa" type="number" value="4.4">η<input id="eta" type="number" value="0.3">Dies<input id="days" type="number" value="30">')}${calcCard('Codi colors','2 xifres + multiplicador','colorCalc()','1r color<select id="c1">${colorOptions()}</select>2n color<select id="c2">${colorOptions()}</select>Multiplicador<select id="cm">${colorOptions()}</select>Tolerància<select id="ct"><option value="0.05">Or ±5%</option><option value="0.10">Plata ±10%</option></select>')}</div><div id="calcOut" class="card"></div>`}
function calcCard(t,f,fn,inputs){return `<div class="card"><h3>${t}</h3><div class="formula">${f}</div><label>${inputs}</label><button class="btn primary" onclick="${fn}">Calcular</button></div>`}
function out(s){$('#calcOut').innerHTML=s}
function ohmCalc(){let R=+$('#r').value,I=+$('#i').value;out(`<div class="result">V = ${I}·${R} = ${(I*R).toFixed(3)} V</div>`)}
function peCalc(){let P=+$('#pk').value,t=+$('#th').value;out(`<div class="result">E = ${P}·${t} = ${(P*t).toFixed(3)} kWh</div>`)}
function seriesCalc(){let a=$('#rs').value.split(',').map(Number);let R=a.reduce((x,y)=>x+y,0),V=+$('#vs').value,I=V/R;out(`<div class="result">Req=${R} Ω · I=${I.toFixed(3)} A · P=${(V*I).toFixed(3)} W</div>`)}
function waterCalc(){let Q=+$('#qj').value,m=+$('#mk').value,Ti=+$('#ti').value;let dT=Q/(m*4180);out(`<div class="result">ΔT=${dT.toFixed(2)} °C · Tf=${(Ti+dT).toFixed(2)} °C</div>`)}
function solarCalc(){let H=+$('#hh').value,A=+$('#aa').value,e=+$('#eta').value,d=+$('#days').value;out(`<div class="result">E=${(H*A*e*d).toFixed(2)} kWh</div>`)}
const colors={negre:0,marró:1,vermell:2,taronja:3,groc:4,verd:5,blau:6,violeta:7,gris:8,blanc:9};
function colorOptions(){return Object.keys(colors).map(c=>`<option value="${c}">${c}</option>`).join('')}
function colorCalc(){let v=(10*colors[$('#c1').value]+colors[$('#c2').value])*Math.pow(10,colors[$('#cm').value]);let tol=+$('#ct').value;out(`<div class="result">Valor nominal: ${v} Ω · mínim ${(v*(1-tol)).toFixed(2)} Ω · màxim ${(v*(1+tol)).toFixed(2)} Ω</div>`)}
function renderPractice(){let e=EXERCISES[Math.floor(Math.random()*EXERCISES.length)];app.innerHTML=`<h2>Pràctica ràpida</h2><div class="card"><h3>${e.theme}</h3><p>${e.statement}</p><button class="btn primary" onclick="openExercise('${e.id}',false)">Treballar aquest exercici</button><button class="btn" onclick="renderPractice()">Un altre</button></div>`}
function renderTeacher(){app.innerHTML=`<h2>Docent</h2><div class="grid"><div class="card"><h3>Preparar classe</h3><p>Tria un tema i genera un dossier d’alumne o solucionari.</p>${filters()}<button class="btn primary" onclick="printDossier(false)">Imprimir dossier alumne</button> <button class="btn" onclick="printDossier(true)">Imprimir solucionari docent</button></div><div class="card"><h3>Recomanació d’ús</h3><ol><li>Comença amb N1-N2 per introduir.</li><li>Fes un N3 a la pissarra.</li><li>Deixa N4 com ampliació o repàs.</li></ol></div></div>`}
function printDossier(teacher){let list=filtered();let w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:"Times New Roman",serif;margin:28px}.ex{page-break-inside:avoid;border-bottom:1px solid #999;margin-bottom:20px;padding-bottom:12px}.space{height:80px;border:1px solid #bbb}</style></head><body><h1>${teacher?'Solucionari docent':'Dossier alumne'}</h1>${list.map(e=>`<div class="ex"><h2>${e.theme}</h2><p><b>${e.exam}</b> · ${e.level}</p><p>${e.statement}</p>${teacher?`<p><b>Solució:</b> ${e.solution}</p>`:'<div class="space"></div>'}</div>`).join('')}</body></html>`);w.document.close();w.print();}
function renderProgress(){let p=JSON.parse(localStorage.ti1progress||'[]');app.innerHTML=`<h2>Progrés local</h2><div class="card"><p>Registres guardats en aquest navegador: <b>${p.length}</b></p><button class="btn" onclick="localStorage.removeItem('ti1progress');render()">Esborrar progrés</button><button class="btn" onclick="exportProgress()">Exportar JSON</button></div><div class="grid">${p.slice(-20).reverse().map(x=>{let e=EXERCISES.find(e=>e.id===x.id)||{};return `<div class="card"><h3>${e.theme||x.id}</h3><p>${new Date(x.at).toLocaleString()}</p><p>Puntuació orientativa: ${x.score??'sense puntuació'}</p></div>`}).join('')}</div>`}
function exportProgress(){let blob=new Blob([localStorage.ti1progress||'[]'],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='progres_ti1batx.json';a.click();}
function renderHelp(){app.innerHTML=`<h2>Ajuda</h2><div class="grid"><div class="card"><h3>Per a l’alumnat</h3><p>Obre un exercici, identifica dades, escriu la resposta de cada pas i compara amb la solució.</p></div><div class="card"><h3>Per al docent</h3><p>Filtra per tema, imprimeix dossier sense solució o solucionari. Usa els nivells N1-N4 per graduar la dificultat.</p></div><div class="card"><h3>Instal·lació</h3><p>Publica els fitxers a GitHub Pages. Després de la primera càrrega, la PWA funciona offline gràcies al Service Worker.</p></div></div>`}
init();
